'use client';
import {useState,type FormEvent} from 'react';
import {Button,Modal,Field,ErrorMessage} from '@/components/ui';
import {api,message} from '@/lib/client';
import {useWorkspace} from './context';
import type {TradingAccount} from '@/types/trading';
export function AccountDialog({open,onOpenChange,account}:{open:boolean;onOpenChange:(v:boolean)=>void;account?:TradingAccount}){
 const {refresh,notify}=useWorkspace();const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(event.currentTarget));try{const saved=await api<TradingAccount>(account?`/api/accounts/${account.id}`:'/api/accounts',{method:account?'PATCH':'POST',body:JSON.stringify(data)});await refresh(saved.id);notify(account?'Account updated.':'Account created.');onOpenChange(false);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <Modal open={open} onOpenChange={onOpenChange} title={account?'Edit trading account':'New trading account'} description="Choose the starting balance and result classification for this account."><form onSubmit={submit} className="form-stack"><ErrorMessage error={error}/><Field label="Account name"><input name="name" required maxLength={80} placeholder="Personal trading account" defaultValue={account?.name}/></Field><div className="form-grid"><Field label="Initial balance"><input name="initialBalance" type="number" required min="0.01" max="1000000000000" step="0.01" defaultValue={account?.initialBalance||'6000'}/></Field><Field label="Currency"><select name="currency" defaultValue={account?.currency||'USD'}>{['USD','EUR','GBP','MXN'].map(c=><option key={c}>{c}</option>)}</select></Field></div><Field label="Break-even band" hint="Results inside ± this amount are break-even. They remain included in your net P&L."><input name="breakEvenBand" type="number" required min="0" max="1000000000" step="0.01" defaultValue={account?.breakEvenBand||'15'}/></Field>{account&&<p className="info-note">Changing the starting balance or band recalculates this account’s historical statistics.</p>}<div className="dialog-actions"><Button type="button" variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button loading={busy}>{account?'Save account':'Create account'}</Button></div></form></Modal>;
}
