'use client';
import {useState,useEffect,type FormEvent} from 'react';
import {Save,FolderOpen,Trash2} from 'lucide-react';
import {Button,Modal,Field,ErrorMessage,Empty} from '@/components/ui';
import {api,message} from '@/lib/client';
import {useWorkspace} from './context';
type Scenario={id:string;name:string;kind:'simulation'|'bankroll';input:unknown;createdAt:string};
export function ScenarioActions({kind,input,onLoad}:{kind:'simulation'|'bankroll';input:unknown;onLoad:(input:unknown)=>void}){
 const {notify}=useWorkspace();const [saveOpen,setSaveOpen]=useState(false),[libraryOpen,setLibraryOpen]=useState(false),[items,setItems]=useState<Scenario[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[remove,setRemove]=useState<Scenario|null>(null);
 useEffect(()=>{if(!libraryOpen)return;let live=true;setError('');setBusy(true);api<Scenario[]>('/api/scenarios').then(data=>{if(live)setItems(data.filter(x=>x.kind===kind));}).catch(e=>{if(live)setError(message(e));}).finally(()=>{if(live)setBusy(false);});return ()=>{live=false;};},[libraryOpen,kind]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await api('/api/scenarios',{method:'POST',body:JSON.stringify({kind,name:String(new FormData(e.currentTarget).get('name')),input})});notify('Scenario saved to your workspace.');setSaveOpen(false);}catch(err){setError(message(err));}finally{setBusy(false);}}
 async function deleteScenario(){if(!remove)return;setBusy(true);setError('');try{await api(`/api/scenarios?id=${remove.id}`,{method:'DELETE'});setItems(items.filter(i=>i.id!==remove.id));setRemove(null);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <><Button variant="secondary" onClick={()=>{setError('');setLibraryOpen(true);}}><FolderOpen size={16}/>Saved scenarios</Button><Button variant="secondary" onClick={()=>{setError('');setSaveOpen(true);}}><Save size={16}/>Save</Button><Modal open={saveOpen} onOpenChange={setSaveOpen} title="Save this scenario" description="Keep these inputs so you can revisit the same assumptions."><form onSubmit={save} className="form-stack"><ErrorMessage error={error}/><Field label="Scenario name"><input name="name" required maxLength={80} placeholder={kind==='simulation'?'Conservative risk, 100 operations':'Five-account evaluation'}/></Field><div className="dialog-actions"><Button variant="secondary" type="button" onClick={()=>setSaveOpen(false)}>Cancel</Button><Button loading={busy}>Save scenario</Button></div></form></Modal><Modal open={libraryOpen&&!remove} onOpenChange={setLibraryOpen} title="Saved scenarios" description="Your assumptions, ready to revisit."><ErrorMessage error={error}/>{busy?<p role="status">Loading scenarios…</p>:items.length?<div className="scenario-list">{items.map(item=><div className="scenario-row" key={item.id}><button onClick={()=>{try{onLoad(item.input);setLibraryOpen(false);}catch(e){setError(message(e));}}}><strong>{item.name}</strong><small>{new Date(item.createdAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</small></button><button className="icon-button" aria-label={`Delete ${item.name}`} onClick={()=>setRemove(item)}><Trash2 size={15}/></button></div>)}</div>:<Empty title="No saved scenarios yet" description="Save the inputs you want to compare or revisit."/>}</Modal><Modal open={!!remove} onOpenChange={v=>{if(!v)setRemove(null);}} title="Delete saved scenario?" description={`“${remove?.name}” will be permanently removed.`}><ErrorMessage error={error}/><div className="dialog-actions"><Button variant="secondary" onClick={()=>setRemove(null)}>Keep scenario</Button><Button variant="danger" loading={busy} onClick={deleteScenario}>Delete scenario</Button></div></Modal></>;
}
