import {pgTable,text,timestamp,boolean,integer,numeric,jsonb,index,uniqueIndex,foreignKey,check,bigint} from 'drizzle-orm/pg-core';
import {sql} from 'drizzle-orm';
const created=()=>timestamp('created_at',{withTimezone:true}).notNull().defaultNow();
export const user=pgTable('app_user',{
 id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull().unique(),emailVerified:boolean('email_verified').notNull().default(false),image:text('image'),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
});
export const session=pgTable('auth_session',{
 id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>user.id,{onDelete:'cascade'}),token:text('token').notNull().unique(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),ipAddress:text('ip_address'),userAgent:text('user_agent'),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[index('session_user_idx').on(t.userId)]);
export const account=pgTable('auth_account',{
 id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>user.id,{onDelete:'cascade'}),accountId:text('account_id').notNull(),providerId:text('provider_id').notNull(),accessToken:text('access_token'),refreshToken:text('refresh_token'),idToken:text('id_token'),accessTokenExpiresAt:timestamp('access_token_expires_at',{withTimezone:true}),refreshTokenExpiresAt:timestamp('refresh_token_expires_at',{withTimezone:true}),scope:text('scope'),password:text('password'),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[index('auth_account_user_idx').on(t.userId),uniqueIndex('auth_provider_unique').on(t.providerId,t.accountId)]);
export const verification=pgTable('auth_verification',{id:text('id').primaryKey(),identifier:text('identifier').notNull(),value:text('value').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>[index('verification_identifier_idx').on(t.identifier)]);
export const rateLimit=pgTable('auth_rate_limit',{id:text('id').primaryKey(),key:text('key').notNull().unique(),count:integer('count').notNull(),lastRequest:bigint('last_request',{mode:'number'}).notNull()});
export const tradingAccounts=pgTable('trading_account',{
 id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>user.id,{onDelete:'cascade'}),name:text('name').notNull(),currency:text('currency').notNull().default('USD'),initialBalance:numeric('initial_balance',{precision:24,scale:8}).notNull(),breakEvenBand:numeric('break_even_band',{precision:24,scale:8}).notNull().default('15'),sourceSheet:text('source_sheet'),sourceHash:text('source_hash'),baselineBreakEven:boolean('baseline_break_even').notNull().default(false),riskMetric:text('risk_metric').notNull().default('planned'),lastSequence:integer('last_sequence').notNull().default(0),createdAt:created(),
},t=>[uniqueIndex('trading_owner_unique').on(t.id,t.userId),uniqueIndex('source_import_unique').on(t.userId,t.sourceHash,t.sourceSheet),index('trading_user_idx').on(t.userId),check('positive_initial_balance',sql`${t.initialBalance}>0`),check('nonnegative_band',sql`${t.breakEvenBand}>=0`),check('risk_metric_valid',sql`${t.riskMetric} IN ('planned','average-win')`)]);
export const trades=pgTable('trade',{
 id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>user.id,{onDelete:'cascade'}),accountId:text('account_id').notNull(),sequence:integer('sequence').notNull(),date:text('date'),symbol:text('symbol').notNull().default(''),riskPercent:numeric('risk_percent',{precision:12,scale:8}),rewardRisk:numeric('reward_risk',{precision:16,scale:8}),duration:numeric('duration',{precision:16,scale:4}),pnl:numeric('pnl',{precision:24,scale:8}),notes:text('notes').notNull().default(''),feelings:text('feelings').notNull().default(''),evidenceUrl:text('evidence_url').notNull().default(''),strategy:text('strategy').notNull().default(''),direction:text('direction').notNull().default(''),session:text('session').notNull().default(''),tags:text('tags').notNull().default(''),sourceRow:integer('source_row'),version:integer('version').notNull().default(1),createdAt:created(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[foreignKey({columns:[t.accountId,t.userId],foreignColumns:[tradingAccounts.id,tradingAccounts.userId]}).onDelete('cascade'),uniqueIndex('trade_sequence_unique').on(t.accountId,t.sequence),index('trade_account_sequence_idx').on(t.userId,t.accountId,t.sequence),index('trade_date_idx').on(t.userId,t.accountId,t.date),check('risk_percent_range',sql`${t.riskPercent}>=0 AND ${t.riskPercent}<=1`),check('trade_positive_sequence',sql`${t.sequence}>0`),check('trade_nonnegative_duration',sql`${t.duration}>=0`),check('trade_nonnegative_reward',sql`${t.rewardRisk}>=0`),check('trade_valid_direction',sql`${t.direction} IN ('','long','short')`)]);
export const strategies=pgTable('strategy',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>user.id,{onDelete:'cascade'}),name:text('name').notNull(),createdAt:created()},t=>[uniqueIndex('strategy_name_unique').on(t.userId,t.name)]);
export const scenarios=pgTable('scenario',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>user.id,{onDelete:'cascade'}),name:text('name').notNull(),kind:text('kind').notNull(),input:jsonb('input').notNull(),createdAt:created()},t=>[index('scenario_user_idx').on(t.userId),check('scenario_kind_valid',sql`${t.kind} IN ('simulation','bankroll')`)]);
export const preferences=pgTable('user_preference',{userId:text('user_id').primaryKey().references(()=>user.id,{onDelete:'cascade'}),theme:text('theme').notNull().default('system'),selectedAccountId:text('selected_account_id'),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow()},t=>[check('preference_theme_valid',sql`${t.theme} IN ('light','dark','system')`)]);
