'use client';
import Link from 'next/link';
import {ArrowRight,BarChart3,BookOpen,Calculator,ChevronRight,Landmark,ShieldCheck,Shuffle} from 'lucide-react';
import {Brand} from '@/components/app-shell';
import {LanguageSelect,ThemeSelect} from '@/components/preference-controls';
import {useLanguage,type MessageKey} from '@/lib/i18n';

function ProductFrame({label,kind='chart'}:{label:string;kind?:'chart'|'table'|'calculator'}){
 return <figure className={`landing-frame ${kind}`} data-placeholder={label}><figcaption><span className="frame-dot"/><span>{label}</span><small>16:10 / REPLACEABLE MEDIA</small></figcaption><div className="frame-canvas" aria-label={label}>{kind==='chart'?<><div className="frame-metrics"><span/><span/><span/><span/></div><svg viewBox="0 0 600 210" role="img" aria-label="Illustrative equity curve"><path className="frame-grid" d="M0 35H600M0 88H600M0 141H600M0 194H600"/><path className="frame-line ghost" d="M0 178L48 147 97 160 148 104 196 128 250 89 305 111 353 65 401 93 451 41 503 57 552 29 600 44"/><path className="frame-line" d="M0 188L48 164 97 174 148 128 196 143 250 105 305 124 353 88 401 103 451 65 503 74 552 43 600 51"/></svg></>:kind==='table'?<div className="frame-table">{Array.from({length:6},(_,i)=><div key={i}><span/><span/><span/><span className={i%3===1?'loss':''}/></div>)}</div>:<div className="frame-calculator"><div><span/><span/><span/><span/></div><aside><b>1.00%</b><strong>$100.00</strong><span/></aside></div>}</div></figure>;
}
const faqs=Array.from({length:7},(_,i)=>[`landing.faq${i+1}`,`landing.faq${i+1}a`] as [MessageKey,MessageKey]);
export function LandingPage(){const {t}=useLanguage();return <div className="landing-page"><a className="skip-link" href="#landing-main">{t('app.skip')}</a><header className="landing-header"><Link href="/" aria-label="TRADEDATA home"><Brand/></Link><nav aria-label="Public navigation"><a href="#product">{t('nav.product')}</a><a href="#how">{t('nav.how')}</a><a href="#analytics">{t('nav.analytics')}</a><a href="#simulation">{t('nav.simulation')}</a><a href="#faq">{t('nav.faq')}</a></nav><div className="landing-actions"><LanguageSelect compact/><ThemeSelect compact/><Link className="landing-login" href="/login">{t('nav.login')}</Link><Link className="button primary landing-start" href="/register">{t('nav.start')}<ArrowRight size={15}/></Link></div></header><main id="landing-main">
 <section className="landing-hero" id="product"><div className="hero-copy"><span className="eyebrow">{t('landing.eyebrow')}</span><h1>{t('landing.titleA')}<br/><span>{t('landing.titleB')}</span></h1><p>{t('landing.lead')}</p><div className="hero-actions"><Link className="button primary" href="/register">{t('landing.primary')}<ArrowRight size={16}/></Link><a className="button secondary" href="#how">{t('landing.secondary')}</a></div><small>{t('landing.proof')}</small></div><div className="hero-stage"><div className="hero-axis"><span>01</span><span>{t('landing.signal')}</span><span>100</span></div><ProductFrame label={t('landing.preview')}/></div></section>
 <section className="landing-section landing-how" id="how"><div className="section-intro"><span className="eyebrow">01 / PROCESS</span><h2>{t('landing.howTitle')}</h2><p>{t('landing.howText')}</p></div><ol>{([['landing.step1','landing.step1Text'],['landing.step2','landing.step2Text'],['landing.step3','landing.step3Text']] as [MessageKey,MessageKey][]).map(([title,body],i)=><li key={title}><span>0{i+1}</span><h3>{t(title)}</h3><p>{t(body)}</p></li>)}</ol></section>
 <section className="landing-feature"><div className="feature-copy"><BookOpen size={22}/><span className="eyebrow">02 / JOURNAL</span><h2>{t('landing.journal')}</h2><p>{t('landing.journalText')}</p><Link href="/register">{t('landing.cta')}<ChevronRight size={16}/></Link></div><ProductFrame label={t('landing.journalImage')} kind="table"/></section>
 <section className="landing-feature reverse" id="analytics"><div className="feature-copy"><BarChart3 size={22}/><span className="eyebrow">03 / ANALYTICS</span><h2>{t('landing.statistics')}</h2><p>{t('landing.statisticsText')}</p></div><ProductFrame label={t('landing.statsImage')}/></section>
 <section className="landing-feature"><div className="feature-copy"><Calculator size={22}/><span className="eyebrow">04 / RISK</span><h2>{t('landing.calculator')}</h2><p>{t('landing.calculatorText')}</p></div><ProductFrame label={t('landing.calculatorImage')} kind="calculator"/></section>
 <section className="landing-simulation" id="simulation"><div className="section-intro"><Shuffle size={22}/><span className="eyebrow">05 / PROBABILITY</span><h2>{t('landing.monte')}</h2><p>{t('landing.monteText')}</p></div><ProductFrame label={t('landing.monteImage')}/></section>
 <section className="landing-feature reverse" id="funded"><div className="feature-copy"><Landmark size={22}/><span className="eyebrow">06 / FUNDED ACCOUNTS</span><h2>{t('landing.fundedTitle')}</h2><p>{t('landing.fundedText')}</p></div><ProductFrame label={t('landing.fundedImage')} kind="table"/></section>
 <section className="landing-philosophy" aria-label="TRADEDATA principles">{([['landing.data','landing.dataText'],['landing.discipline','landing.disciplineText'],['landing.probability','landing.probabilityText'],['landing.transparency','landing.transparencyText']] as [MessageKey,MessageKey][]).map(([title,body],i)=><article key={title}><span>0{i+1}</span><h2>{t(title)}</h2><p>{t(body)}</p></article>)}</section>
 <section className="landing-showcase"><div className="section-intro"><span className="eyebrow">07 / THE WORKSPACE</span><h2>{t('landing.productTitle')}</h2><p>{t('landing.productText')}</p></div><div className="showcase-grid"><ProductFrame label={t('landing.journalImage')} kind="table"/><ProductFrame label={t('landing.statsImage')}/><ProductFrame label={t('landing.monteImage')}/></div></section>
 <section className="landing-future"><ShieldCheck size={25}/><div><span className="eyebrow">TRADEDATA / NEXT</span><h2>{t('landing.future')}</h2><p>{t('landing.futureText')}</p></div><Link className="button primary" href="/register">{t('landing.cta')}<ArrowRight size={16}/></Link></section>
 <section className="landing-faq" id="faq"><div className="section-intro"><span className="eyebrow">08 / FAQ</span><h2>{t('landing.faqTitle')}</h2></div><div>{faqs.map(([question,answer],i)=><details key={question} open={i===0}><summary>{t(question)}<span>+</span></summary><p>{t(answer)}</p></details>)}</div></section>
 </main><footer className="landing-footer"><div><Brand/><p>{t('landing.footerText')}</p></div><div><strong>{t('nav.product')}</strong><a href="#how">{t('nav.how')}</a><a href="#analytics">{t('nav.analytics')}</a><a href="#simulation">{t('nav.simulation')}</a></div><div><strong>{t('landing.legal')}</strong><span>{t('landing.privacy')}</span><span>{t('landing.terms')}</span></div><div><strong>{t('landing.contact')}</strong><span>{t('landing.noContact')}</span></div><small>{t('landing.copyright')}</small></footer></div>}
