'use client';
import {useState} from 'react';
import {Info,Calculator as CalculatorIcon} from 'lucide-react';
import {PageHeading,Panel,Field} from '@/components/ui';
import {eurusd,xauusd} from '@/lib/calculations/calculator';
import {money,number} from '@/lib/format';
export function Calculator(){const [mode,setMode]=useState<'eurusd'|'xauusd'>('eurusd'),[pips,setPips]=useState('0.6'),[cash,setCash]=useState('55'),[goldPips,setGoldPips]=useState(''),[lots,setLots]=useState('');const result=mode==='eurusd'?(pips!==''&&cash!==''?eurusd(Number(pips),Number(cash)):null):(goldPips!==''&&lots!==''?xauusd(Number(goldPips),Number(lots)):null);
 return <><PageHeading eyebrow="PLAN THE EXPOSURE" title="Trading calculator" description="The workbook’s position and commission calculations, in one place."/><div className="calculator-layout"><Panel title="Trade parameters" description="Updates as you adjust your inputs."><div className="panel-body form-stack"><div className="segmented" role="group" aria-label="Calculator instrument"><button className={mode==='eurusd'?'selected':''} aria-pressed={mode==='eurusd'} onClick={()=>setMode('eurusd')}>EUR/USD</button><button className={mode==='xauusd'?'selected':''} aria-pressed={mode==='xauusd'} onClick={()=>setMode('xauusd')}>XAU/USD</button></div>{mode==='eurusd'?<><Field label="Stop distance (workbook pips)" hint="Uses the source’s multiplier of 100."><input type="number" min="0.000001" max="1000000" step="any" value={pips} onChange={e=>setPips(e.target.value)}/></Field><Field label="Cash at risk ($)" hint="Before the source commission estimate."><input type="number" min="0" max="1000000000" step="any" value={cash} onChange={e=>setCash(e.target.value)}/></Field></>:<><Field label="Stop distance (workbook pips)"><input type="number" min="0" max="1000000" step="any" placeholder="Enter distance" value={goldPips} onChange={e=>setGoldPips(e.target.value)}/></Field><Field label="Position size (lots)"><input type="number" min="0" max="1000000" step="any" placeholder="Enter lots" value={lots} onChange={e=>setLots(e.target.value)}/></Field></>}</div></Panel><Panel title={mode==='eurusd'?'Position size':'Cash exposure'} actions={<CalculatorIcon size={20} className="muted"/>}><div className="calculation-results"><span>{mode==='eurusd'?'Calculated lots':'Calculated cash at risk'}</span><strong>{result?(mode==='eurusd'?number(result.lots,6):money(result.cash)):'—'}</strong><dl className="stat-list"><div><dt>Cash at risk</dt><dd>{money(result?.cash??null)}</dd></div><div><dt>Estimated commission</dt><dd>{money(result?.fees??null)}</dd></div><div><dt>Total including commission</dt><dd>{money(result?.total??null)}</dd></div></dl><div className="formula-note">{mode==='eurusd'?<>Lots = cash ÷ (pips × 100)<br/>Total = cash + (lots × $5)</>:<>Cash = pips × 100 × lots<br/>Total = cash + (lots × $3.32)</>}</div>{!result&&<p className="disclosure-note" role="status">Enter valid values{mode==='eurusd'?', including a stop distance greater than zero':''}, to calculate the result.</p>}</div></Panel></div><div className="disclosure-note"><Info size={16}/><span>The 100 multiplier and commissions reproduce Calculators!B5, D5, H5 and I5. They are broker-specific workbook conventions; confirm the units and actual commission with your broker. Calculated precision is preserved; displayed lots are rounded to six decimals.</span></div></>;
}
