'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useTheme} from 'next-themes';
import {useState} from 'react';
import {LayoutDashboard,BookOpen,ChartNoAxesCombined,Calculator,Shuffle,Landmark,Settings,Sun,Moon,Menu,ChevronDown,Plus,LogOut,Upload,Check,X,ArrowUpRight} from 'lucide-react';
import {useWorkspace} from '@/features/workspace/context';
import {AccountDialog} from '@/features/workspace/account-dialog';
import {ImportDialog} from '@/features/workspace/import-dialog';
import {Button,Modal,ErrorMessage} from './ui';
import {authClient} from '@/lib/auth-client';
import {message} from '@/lib/client';
const navigation=[{href:'/dashboard',label:'Overview',icon:LayoutDashboard},{href:'/journal',label:'Trading journal',icon:BookOpen},{href:'/statistics',label:'Statistics',icon:ChartNoAxesCombined},{href:'/calculator',label:'Calculator',icon:Calculator},{href:'/monte-carlo',label:'Monte Carlo',icon:Shuffle},{href:'/funded-accounts',label:'Funded accounts',icon:Landmark}];
export function Brand(){return <div className="brand"><span className="brand-mark" aria-label="Temporary TRADEDATA icon"><ChartNoAxesCombined size={22} strokeWidth={2.4}/></span><span>TRADE<span className="brand-light">DATA</span></span></div>;}
export function AppShell({children,user}:{children:React.ReactNode;user:{name:string;email:string}}){
 const pathname=usePathname(),router=useRouter(),{resolvedTheme,setTheme}=useTheme();const {accounts,account,select,loading,error,notice,notify}=useWorkspace();
 const [menu,setMenu]=useState(false),[newAccount,setNewAccount]=useState(false),[importOpen,setImportOpen]=useState(false),[logoutError,setLogoutError]=useState('');
 const title=navigation.find(n=>n.href===pathname)?.label||'Settings';
 const links=<><div className="nav-caption">WORKSPACE</div><nav aria-label="Main navigation">{navigation.map(({href,label,icon:Icon})=><Link href={href} key={href} className={`nav-link ${pathname===href?'active':''}`} aria-current={pathname===href?'page':undefined} onClick={()=>setMenu(false)}><Icon size={19}/>{label}{pathname===href&&<span className="nav-marker"/>}</Link>)}</nav><div className="sidebar-bottom"><div className="principle"><span className="eyebrow">A CLEARER PERSPECTIVE</span><p>Data over emotion.</p><span>Record. Review. Refine.</span></div><Link href="/settings" className={`nav-link ${pathname==='/settings'?'active':''}`} onClick={()=>setMenu(false)}><Settings size={19}/>Settings</Link><div className="profile"><span className="avatar">{user.name.slice(0,2).toUpperCase()}</span><div><strong>{user.name}</strong><span>Personal workspace</span></div><button className="icon-button" aria-label="Log out" onClick={async()=>{const result=await authClient.signOut();if(result.error)setLogoutError(result.error.message||'Could not log out.');else {router.push('/login');router.refresh();}}}><LogOut size={17}/></button></div></div></>;
 return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><aside className="sidebar"><Link href="/dashboard" aria-label="TRADEDATA home"><Brand/></Link>{links}</aside><div className="main-wrap"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-only" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu size={22}/></button><span className="desktop-only">Workspace</span><span className="desktop-only breadcrumb-divider">/</span><strong>{title}</strong></div><div className="topbar-actions"><div className="account-picker"><span className="account-symbol"><Landmark size={15}/></span><select value={account?.id||''} aria-label="Trading account" disabled={!accounts.length||loading} onChange={e=>{void select(e.target.value).catch(()=>{});}}>{!accounts.length&&<option value="">No trading accounts</option>}{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><ChevronDown size={14}/></div><button className="icon-button" aria-label="Create trading account" onClick={()=>setNewAccount(true)}><Plus size={18}/></button><span className="toolbar-divider"/><button className="icon-button" aria-label="Toggle color theme" onClick={()=>setTheme(resolvedTheme==='dark'?'light':'dark')}><Sun size={19} className="theme-sun"/><Moon size={19} className="theme-moon"/></button></div></header>{loading&&<div className="loading-line" aria-label="Updating account"/>}<main id="main" className="main-content"><ErrorMessage error={error||logoutError}/>{notice&&<div className="notice" role="status"><Check size={17}/><span>{notice}</span><button className="icon-button" onClick={()=>notify('')} aria-label="Dismiss notification"><X size={16}/></button></div>}{children}</main><footer className="app-footer"><span>TRADEDATA <span className="footer-dot">·</span> Data. Discipline. Probability. Transparency.</span><button onClick={()=>setImportOpen(true)}><Upload size={13}/>Import workbook<ArrowUpRight size={13}/></button></footer></div><Modal open={menu} onOpenChange={setMenu} title="TRADEDATA navigation"><div className="mobile-nav">{links}</div></Modal><AccountDialog key={String(newAccount)} open={newAccount} onOpenChange={setNewAccount}/><ImportDialog open={importOpen} onOpenChange={setImportOpen}/></div>;
}
