'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useState} from 'react';
import {LayoutDashboard,BookOpen,ChartNoAxesCombined,Calculator,Shuffle,Landmark,Settings,Menu,ChevronDown,Plus,LogOut,Upload,Check,X,ArrowUpRight} from 'lucide-react';
import {useWorkspace} from '@/features/workspace/context';
import {AccountDialog} from '@/features/workspace/account-dialog';
import {ImportDialog} from '@/features/workspace/import-dialog';
import {Button,Modal,ErrorMessage} from './ui';
import {authClient} from '@/lib/auth-client';
import {message} from '@/lib/client';
import {useLanguage,type MessageKey} from '@/lib/i18n';
import {LanguageSelect,ThemeSelect} from './preference-controls';
const navigation=[{href:'/dashboard',label:'app.overview',icon:LayoutDashboard},{href:'/journal',label:'app.journal',icon:BookOpen},{href:'/statistics',label:'app.statistics',icon:ChartNoAxesCombined},{href:'/calculator',label:'app.calculator',icon:Calculator},{href:'/monte-carlo',label:'app.monteCarlo',icon:Shuffle},{href:'/funded-accounts',label:'app.funded',icon:Landmark}] as const;
export function Brand(){return <div className="brand"><span className="brand-mark" aria-label="Temporary TRADEDATA icon"><ChartNoAxesCombined size={22} strokeWidth={2.4}/></span><span>TRADE<span className="brand-light">DATA</span></span></div>;}
export function AppShell({children,user}:{children:React.ReactNode;user:{name:string;email:string}}){
 const pathname=usePathname(),router=useRouter(),{t}=useLanguage();const {accounts,account,select,loading,error,notice,notify}=useWorkspace();
 const [menu,setMenu]=useState(false),[newAccount,setNewAccount]=useState(false),[importOpen,setImportOpen]=useState(false),[logoutError,setLogoutError]=useState('');
 const active=navigation.find(n=>n.href===pathname);const title=active?t(active.label as MessageKey):t('app.settings');
 const links=<><div className="nav-caption">{t('app.workspace')}</div><nav aria-label="Main navigation">{navigation.map(({href,label,icon:Icon})=><Link href={href} key={href} className={`nav-link ${pathname===href?'active':''}`} aria-current={pathname===href?'page':undefined} onClick={()=>setMenu(false)}><Icon size={19}/>{t(label)}{pathname===href&&<span className="nav-marker"/>}</Link>)}</nav><div className="sidebar-bottom"><div className="principle"><span className="eyebrow">{t('app.perspective')}</span><p>{t('app.dataEmotion')}</p><span>{t('app.recordReview')}</span></div><Link href="/settings" className={`nav-link ${pathname==='/settings'?'active':''}`} onClick={()=>setMenu(false)}><Settings size={19}/>{t('app.settings')}</Link><div className="profile"><span className="avatar">{user.name.slice(0,2).toUpperCase()}</span><div><strong>{user.name}</strong><span>{t('app.personal')}</span></div><button className="icon-button" aria-label={t('app.logout')} onClick={async()=>{const result=await authClient.signOut();if(result.error)setLogoutError(result.error.message||'Could not log out.');else {router.push('/login');router.refresh();}}}><LogOut size={17}/></button></div></div></>;
 return <div className="app-shell"><a className="skip-link" href="#main">{t('app.skip')}</a><aside className="sidebar"><Link href="/dashboard" aria-label="TRADEDATA home"><Brand/></Link>{links}</aside><div className="main-wrap"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-only" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu size={22}/></button><span className="desktop-only">{t('app.workspace')}</span><span className="desktop-only breadcrumb-divider">/</span><strong>{title}</strong></div><div className="topbar-actions"><div className="account-picker"><span className="account-symbol"><Landmark size={15}/></span><select value={account?.id||''} aria-label={t('app.account')} disabled={!accounts.length||loading} onChange={e=>{void select(e.target.value).catch(()=>{});}}>{!accounts.length&&<option value="">{t('app.noAccounts')}</option>}{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><ChevronDown size={14}/></div><button className="icon-button" aria-label={t('app.newAccount')} onClick={()=>setNewAccount(true)}><Plus size={18}/></button><span className="toolbar-divider"/><LanguageSelect compact/><ThemeSelect compact/></div></header>{loading&&<div className="loading-line" aria-label="Updating account"/>}<main id="main" className="main-content"><ErrorMessage error={error||logoutError}/>{notice&&<div className="notice" role="status"><Check size={17}/><span>{notice}</span><button className="icon-button" onClick={()=>notify('')} aria-label="Dismiss notification"><X size={16}/></button></div>}{children}</main><footer className="app-footer"><span>TRADEDATA <span className="footer-dot">·</span> Data. Discipline. Probability. Transparency.</span><button onClick={()=>setImportOpen(true)}><Upload size={13}/>{t('app.import')}<ArrowUpRight size={13}/></button></footer></div><Modal open={menu} onOpenChange={setMenu} title="TRADEDATA navigation"><div className="mobile-nav">{links}</div></Modal><AccountDialog key={`new-${String(newAccount)}`} open={newAccount} onOpenChange={setNewAccount}/><ImportDialog open={importOpen} onOpenChange={setImportOpen}/></div>;
}
