'use client';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,PieChart,Pie,Cell,BarChart,Bar,ReferenceLine,LineChart,Line,Legend} from 'recharts';
import type {Analytics} from '@/lib/analytics/journal';
import type {SimulationResult} from '@/types/trading';
import {money,number,percent} from '@/lib/format';
const colors={blue:'#4c8dff',green:'#36b88f',red:'#ed7186',muted:'#8693aa'};
const axis={stroke:'var(--text-faint)',fontSize:12,tickLine:false,axisLine:false};
const tooltip={background:'var(--surface-raised)',border:'1px solid var(--border)',borderRadius:10,color:'var(--text)',fontSize:13,boxShadow:'0 8px 30px #0002'};
export function EquityChart({data,currency,growth=false}:{data:Analytics['equity'];currency:string;growth?:boolean}){return <div className="chart equity-chart" role="img" aria-label={`Account ${growth?'return':'equity'} across ${data.length-1} plotted operations`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:12,right:8,bottom:2,left:0}} accessibilityLayer><defs><linearGradient id="equity-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors.blue} stopOpacity={.24}/><stop offset="95%" stopColor={colors.blue} stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--chart-grid)" strokeDasharray="3 5"/><XAxis dataKey="label" {...axis} minTickGap={48} dy={10}/><YAxis {...axis} width={66} domain={['auto','auto']} tickFormatter={v=>growth?`${number(v,1)}%`:new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(v)}/><Tooltip contentStyle={tooltip} cursor={{stroke:'var(--border-strong)'}} formatter={v=>growth?percent(Number(v)):money(Number(v),currency)} labelFormatter={label=>label==='Start'?'Starting balance':`Operation ${label}`}/><Area type="linear" dataKey={growth?'growth':'balance'} name={growth?'Return':'Balance'} stroke={colors.blue} strokeWidth={2.4} fill="url(#equity-fill)" isAnimationActive={false} activeDot={{r:5,stroke:'var(--surface)',strokeWidth:3}}/></AreaChart></ResponsiveContainer></div>;}
export function OutcomeChart({analytics}:{analytics:Analytics}){const data=[{name:'Wins',value:analytics.wins,color:colors.green},{name:'Losses',value:analytics.losses,color:colors.red},{name:'Break-even',value:analytics.breakEven,color:colors.muted}];return <div className="outcome-chart"><div className="donut-wrap" role="img" aria-label={`${analytics.wins} wins, ${analytics.losses} losses, ${analytics.breakEven} break-even trades`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius="73%" outerRadius="90%" paddingAngle={analytics.total>1?5:0} cornerRadius={5} startAngle={90} endAngle={-270} stroke="none" isAnimationActive={false}>{data.map(d=><Cell key={d.name} fill={d.color}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{analytics.total}</strong><span>closed trades</span></div></div><div className="outcome-legend">{data.map(d=><div key={d.name}><span><i style={{background:d.color}}/>{d.name}</span><strong>{d.value}</strong><span>{percent(analytics.total?d.value/analytics.total*100:0,1)}</span></div>)}</div></div>;}
export function DrawdownChart({data}:{data:Analytics['equity']}){return <div className="chart drawdown-chart" role="img" aria-label="Drawdown in percentage points of starting capital"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:5,right:8,left:0,bottom:0}} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--chart-grid)" strokeDasharray="3 5"/><XAxis dataKey="label" {...axis} hide/><YAxis {...axis} width={48} tickFormatter={v=>`${number(v,1)}%`} domain={['auto',0]}/><Tooltip contentStyle={tooltip} formatter={v=>percent(Number(v))} labelFormatter={l=>`Operation ${l}`}/><Area dataKey="drawdown" name="Drawdown" type="linear" stroke={colors.red} strokeWidth={1.5} fill={colors.red} fillOpacity={.12} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>;}
export function SymbolChart({data}:{data:Analytics['bySymbol']}){return <div className="chart medium-chart" role="img" aria-label="Wins, losses and break-even trades by instrument"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} barSize={35} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="symbol" {...axis}/><YAxis {...axis} allowDecimals={false} width={35}/><Tooltip contentStyle={tooltip}/><Legend iconType="circle" iconSize={8} wrapperStyle={{fontSize:12,paddingTop:12}}/><Bar dataKey="win" name="Wins" stackId="outcome" fill={colors.green} isAnimationActive={false}/><Bar dataKey="loss" name="Losses" stackId="outcome" fill={colors.red} isAnimationActive={false}/><Bar dataKey="breakeven" name="Break-even" stackId="outcome" fill={colors.muted} radius={[4,4,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;}
export function PnlChart({data,currency}:{data:Analytics['equity'];currency:string}){return <div className="chart medium-chart" role="img" aria-label="Net result of each operation"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.filter(d=>d.sequence>0)} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis {...axis} dataKey="label" minTickGap={25}/><YAxis {...axis} width={48}/><ReferenceLine y={0} stroke="var(--border-strong)"/><Tooltip contentStyle={tooltip} formatter={v=>money(Number(v),currency)}/><Bar dataKey="pnl" name="Net P&L" radius={[3,3,0,0]} isAnimationActive={false}>{data.filter(d=>d.sequence>0).map((p,i)=><Cell key={i} fill={p.pnl>=0?colors.green:colors.red}/>)}</Bar></BarChart></ResponsiveContainer></div>;}
export function MonthlyChart({data,currency}:{data:Analytics['monthly'];currency:string}){return <div className="chart medium-chart" role="img" aria-label="Monthly net profit and loss"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis {...axis} dataKey="month"/><YAxis {...axis} width={55}/><Tooltip contentStyle={tooltip} formatter={v=>money(Number(v),currency)}/><ReferenceLine y={0} stroke="var(--border-strong)"/><Bar name="Profits" dataKey="profit" fill={colors.green}/><Bar name="Losses" dataKey="loss" fill={colors.red}/></BarChart></ResponsiveContainer></div>;}
export function SimulationChart({result}:{result:SimulationResult}){
 const max=Math.max(...result.paths.map(p=>p.values.length));const data=Array.from({length:max},(_,i)=>{const row:Record<string,number|null>={operation:i};result.paths.forEach((p,j)=>{row[`p${j}`]=p.values[i]===undefined?null:p.values[i]*100;});return row;});
 return <div className="chart simulation-chart" role="img" aria-label={`First ${result.paths.length} simulated account paths out of ${result.total}. Target ${percent(result.input.target*100)}.`}><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:18,right:20,bottom:6,left:0}} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--chart-grid)" strokeDasharray="3 5"/><XAxis {...axis} dataKey="operation" minTickGap={35}/><YAxis {...axis} width={52} tickFormatter={v=>`${number(v,1)}%`}/><ReferenceLine y={result.input.target*100} stroke={colors.green} strokeDasharray="5 5" label={{value:'TARGET',position:'insideTopRight',fill:colors.green,fontSize:10}}/>{!result.input.trailing&&<ReferenceLine y={-result.input.maxDrawdown*100} stroke={colors.red} strokeDasharray="5 5" label={{value:'LIMIT',position:'insideBottomRight',fill:colors.red,fontSize:10}}/>}<Tooltip contentStyle={tooltip} content={({active,payload,label})=>active&&payload?.length?<div className="chart-tooltip"><strong>Operation {label}</strong>{payload.slice(0,5).map((p,i)=><div key={i} style={{color:p.color}}>{p.name}: {percent(Number(p.value))}</div>)}<small>Showing up to 5 paths at this point</small></div>:null}/>{result.paths.map((p,i)=><Line key={i} name={`Account ${i+1}`} dataKey={`p${i}`} type="linear" stroke={p.status==='passed'?colors.green:p.status==='failed'?colors.red:colors.blue} strokeOpacity={.55} strokeWidth={1.2} dot={false} activeDot={{r:3}} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>;
}
export function DistributionChart({result}:{result:SimulationResult}){const min=result.worstReturn,max=result.bestReturn,step=(max-min)/12||.01;const bins=Array.from({length:12},(_,i)=>({label:percent((min+i*step)*100,1),count:0}));result.endingReturns.forEach(v=>bins[Math.min(11,Math.floor((v-min)/step))].count++);return <div className="chart medium-chart" role="img" aria-label="Distribution of final simulated returns"><ResponsiveContainer width="100%" height="100%"><BarChart data={bins} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="label" {...axis} minTickGap={20}/><YAxis {...axis} width={35} allowDecimals={false}/><Tooltip contentStyle={tooltip}/><Bar dataKey="count" name="Accounts" fill={colors.blue} radius={[4,4,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;}
