'use client';
import * as Dialog from '@radix-ui/react-dialog';
import {X,LoaderCircle,ArrowUpRight} from 'lucide-react';
import type {ReactNode,ButtonHTMLAttributes} from 'react';
export function Button({children,className='',loading=false,variant='primary',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{loading?:boolean;variant?:'primary'|'secondary'|'ghost'|'danger'}){return <button {...props} disabled={props.disabled||loading} className={`button ${variant} ${className}`}>{loading&&<LoaderCircle size={16} className="spin"/>}{children}</button>;}
export function Modal({open,onOpenChange,title,description,children,wide=false}:{open:boolean;onOpenChange:(open:boolean)=>void;title:string;description?:string;children:ReactNode;wide?:boolean}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className={`dialog-content ${wide?'wide':''}`} aria-describedby={description?'dialog-description':undefined}><div className="dialog-heading"><div><Dialog.Title>{title}</Dialog.Title>{description&&<Dialog.Description id="dialog-description">{description}</Dialog.Description>}</div><Dialog.Close className="icon-button" aria-label="Close dialog"><X size={20}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function Field({label,hint,children,className=''}:{label:string;hint?:string;children:ReactNode;className?:string}){return <label className={`field ${className}`}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function ErrorMessage({error}:{error:string}){return error?<div className="error-message" role="alert">{error}</div>:null;}
export function PageHeading({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="heading-actions">{actions}</div>}</div>;}
export function Panel({title,description,actions,children,className=''}:{title?:string;description?:string;actions?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}>{title&&<div className="panel-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{actions}</div>}{children}</section>;}
export function Metric({label,value,detail,tone,icon}:{label:string;value:string;detail?:string;tone?:'positive'|'negative';icon?:ReactNode}){return <div className="metric"><div className="metric-label">{label}{icon}</div><div className={`metric-value ${tone||''}`}>{value}</div>{detail&&<div className="metric-detail">{detail}</div>}</div>;}
export function Empty({title,description,action,icon}:{title:string;description:string;action?:ReactNode;icon?:ReactNode}){return <div className="empty-state"><div className="empty-icon">{icon||<ArrowUpRight size={25}/>}</div><h2>{title}</h2><p>{description}</p>{action}</div>;}
